---
services:
  db:
    image: postgres:alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - 5432:5432

    expose:
      - 5432

    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
